services:
  db-init:
    build:
      context: .
      dockerfile: sql/Dockerfile
    container_name: cooking-db-init
    env_file:
      - .env

  user-service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    container_name: cooking-user-service
    env_file:
      - .env
    ports:
      - "8000:8000"

  competition-service:
    build:
      context: .
      dockerfile: competition_service/Dockerfile
    container_name: cooking-competition-service
    env_file:
      - .env
    ports:
      - "8001:8001"

  recipe-service:
    build:
      context: .
      dockerfile: recipe_service/Dockerfile
    container_name: cooking-recipe-service
    env_file:
      - .env
    ports:
      - "8002:8002"

  feedback-service:
    build:
      context: .
      dockerfile: feedback_service/Dockerfile
    container_name: cooking-feedback-service
    env_file:
      - .env
    environment:
      SB_QUEUE_NAME: alekseikarpukovich
    ports:
      - "8003:8003"
